### ISSUE TITLE
Vibration workaround 

### ISSUE THREAD

**Issue by R9TRH** [januarydayfin/MiDndWorkaround#1]
Hello! Thanks for a final working workaround for DND issue. It works perfectly for me
However, I have a suggestion 
You can implement an option to toggle "vibration" with DND; which is useful because normal silent mode just silents audio but vibration will remain working.
Thanks in advance! Keep it up 👍

**Comment by januarydayfin** [comment]
Hi, thank you for your feedback! I can add vibro switch on dnd for you :) See in next update :)

**Comment by januarydayfin** [comment]
https://github.com/januarydayfin/MiDndWorkaround/releases/tag/1.03
